requirements: | 
functional:
- Защита конфиденциальной информации о  пользователе. 1.1
- Переведено с помощью www.DeepL.com/Translator (бесплатная версия). 1.2
- Поиск товаров по символам в названии товара. 1.3.1
- Поиск товаров по категории товаров. 1.3.2
- Фильтрация товаров по цене. 1.4.1
- Фильтрация товаров по цвету. 1.4.2
- Фильтрация товаров по размеру. 1.4.3
- Фильтрация товаров по категории товара. 1.4.4
- Фильтрация товаров по бренду товара 1.4.5
- Фильтрация товаров по наличию товара. 1.4.6
- Фильтрация товаров по рейтингу. 1.4.7
- Пользователю отображено краткое название товара в ячейке товара. 1.6.1
- Пользователю отображено основное изображение товара в ячейке товара. 1.6.2
- Пользователю отображена краткое описание товара в ячейке товара. 1.6.3
- Пользователю отображена цена товара в ячейке товара. 1.6.4
- Пользователю отображена цена со скидкой в ячейке товара. 1.6.5
- Пользователю отображено количество товаров в наличии в ячейке товара. 1.6.6
- Пользователю отображена кнопка "В корзину"/"Add to cart" в ячейке товара. 1.6.7
- При просмотре подробной информации о товаре пользователю отображено полное название товара 1.7.1
- При просмотре подробной информации о товаре пользователю отображено основное изображение товара. 1.7.2
- При просмотре подробной информации о товаре пользователю отображена полное описание о товара. 1.7.3
- При просмотре подробной информации о товаре пользователю отображен рейтинг товара. 1.7.4
- При просмотре подробной информации о товаре пользователю отображена цена товара. 1.7.5
- При просмотре подробной информации о товаре пользователю отображена цена товара со скидкой. 1.7.6
- При просмотре подробной информации о товаре пользователю отображен процент скидки. 1.7.7
- При просмотре подробной информации о товаре пользователю отображено количество товара в наличии. 1.7.8
- При просмотре подробной информации о товаре пользователю отображена кнопка "В корзину"/"Add to cart". 1.7.9
- При просмотре подробной информации о товаре пользователю отображены дополнительные изображения товара. 1.7.10
- При просмотре подробной информации о товаре пользователю отображен тэг категории товара. 1.7.12
- Пользователь имеет возможность добавлять товары в корзину нажатием кнопки "В корзину"/"Add to cart". 1.8
- Пользователь имеет возможность просматривать содержимое корзины. 1.9
- На веб-странице корзины пользователю отображена кнопка "Очистить корзину"/"Clear cart". 1.9.1
- На веб-странице корзины пользователю отображена кнопка "Продолжить покупки"/"Continue shopping". 1.9.2
- На веб-странице корзины пользователю отображена кнопка
- На веб-странице корзины пользователю отображена кнопка

Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть способен обрабатывать большое количество трафика.
- Сайт должен быть доступен на различных устройствах.
- Сайт должен иметь мобильную версию.
implicit:
- На главной странице товары отображены в виде списка ячеек товаров. 1.5.1
- Сайт имеет фасетную навигацию. 1.5.2
- Пользователь имеет возможность просматирвать список в виде ячеек товаров. 1.6
- Пользователь имеет возможность просматривать подробную информацию о товаре. 1.7
- При просмотре подробной информации о товаре основные, дополнительные изображения представлены в виде превью. 1.7.11
- Просматривая страницу подробной информации о товаре, нажимая на тэг категории товара, пользователю отображается список товаров данной категории. 1.7.13
- Нажатием кнопки "В корзину"/"Add to cart" пользователь попадает на веб-страницу корзины пользователя. 1.10
- Нажатием кнопки "Магазин"/"Store" пользователь возвращается на главную веб-страницу приложения. 1.11
- Нажатием на accordeon "Язык"/"Language" пользователь может выбрать язык отображения информации в WEB-приложении из выпадающего списка. 1.12
- В выпадающем списоке accordeon "Язык"/"Language" пользователю отображена кнопка "Russian". 1.12.1
- При нажатии на кнопку "Russian" в выпадающем списоке accordeon "Язык"/"Language" текстовая информация на веб страницах должна быть отображена на русском языке. 1.12.1.1
- В выпадающем списоке accordeon "Язык"/"Language" пользователю отображена кнопка "English". 1.12.2
- При нажатии на кнопку "English" в выпадающем списоке accordeon "Язык"/"Language" текстовая информация на веб страницах должна быть отображена на английском языке. 1.12.2.1
- При смене языкового отображения веб-страницы название товара остается неизменным. 1.13.1
- При смене языкового отображения веб-страницы название производителя остается неизменным. 1.13.2
- Пользователю отображен бренд товара в ячейке товара. 1.6.8
- При просмотре подробной информации о товаре пользователю отображен бренд товара. 1.7.13
- 
- 

Ни одному другому пользователю не отражены персональные данные другого пользователя.
- Ни одному другому пользователю не отражено содержимое корзины другого пользователя.
- На момент релиза сайт должен быть совместим с последними версиями десктопных браузеров.
- На момент релиза сайт должен быть совместим с последними версиями мобильных браузеров.
- Сайт должен быть доступен на устройствах, поддерживающих последнюю версию десктопных браузеров на момент релиза.
- Сайт должен быть доступен на устройствах, поддерживающих последнюю версию мобильных браузеров на момент релиза.
- Сайт должен иметь десктопную версию.
- Пользователь может фильтровать товары по нескольким выбранным характеристикам товара одновременно.
- Пользователь может фильтровать товары по одной характеристике товара.
- Товары фильтруются по цене, цвету, размеру, категориям, ключевым словам в описании, ключевым словам в названии, цене, цене со скидкой, производителю, наличию, рейтингу.
- Пользователю отображены товары доступные для просмотра.
- Пользователю не отражены товары не доступные для просмотра.
- Корзина имеет отдельную страницу.
- Пользователь может удалять товары из корзины.
- Корзина должна отображать сумму стоимости товаров, находящихся в корзине.
- Корзина должна отображать информацию о товарах название, количество в наличии, количество в корзине, цену товара, цену товара со скидкой.
- Из корзины пользователь может перейти на страницу оплаты.
- Из корзины пользователь может вернуться на страницу каталога товаров.
- Корзина хранится в сессии браузера.
- Оплата товара производится на отдельной странице.
- Подробная информация о товаре может содержать изображение товара, название, категорию, цену, цену со скидкой, описание, рейтинг, количество товара в наличии, процент скидки.
- Данные сайта должны быть отражены на английском, русском языке.
- Сайт должен иметь возможность смены языка отображения.
- Пользователи должны иметь возможность оценивать товар посредством составления рейтинга в каталоге товаров.
