requirements: | 
functional:
- Пользователь может просматривать веб-страницу каталога товаров. 1
- Пользователь может просматривать ячейки товаров. 1.1
- Пользователь может переходить на веб-страницу товара. 1.2
- Пользователь может просматривать веб-страницу товара. 1.2.1
- Пользователь может переходить на веб-страницу корзины. 1.3
- Пользователь может просматривать содержимое корзины. 1.3.1
- Пользователь может регистрироваться. 1.4
- Пользователь может авторизоваться. 1.5
- Ни одному другому пользователю не отражено содержимое корзины другого пользователя. 1.6
- Ни одному другому пользователю не отражены персональные данные другого пользователя. 1.7
- Защита конфиденциальной информации о пользователе. 1.8
- Зарегестрированный пользователь может выставлять рейтинг товаров виде оценки натуральным числом по "5"ти бальной шкале, от "1" до "5". 1.9
- Фильтрация товаров по символам в названии товара. 3.2
- Фильтрация товаров по символам в производителе товара. 3.3
- Фильтрация товаров по символам в описании товара. 3.4
- Фильтрация товаров по цене. 3.5
- Фильтрация товаров по цвету. 3.6
- Фильтрация товаров по размеру. 3.7
- Фильтрация товаров по категории товара. 3.8
- Фильтрация товаров по производителю товара. 3.9
- Фильтрация товаров по наличию товара. 3.10
- Фильтрация товаров по рейтингу. 3.11
- На веб-странице корзины пользователю отображена кнопка "Очистить корзину"/"Clear cart". 6
- На веб-странице корзины пользователю отображена кнопка "Продолжить покупки"/"Continue shopping". 6.1
- На веб-странице корзины пользователю отображена кнопка "Оформить заказ"/"Checkout". 6.2
- На веб-странице корзины пользователю отображена сумма стоимости добавленных в корзину товаров с учетом скидки. 6.3
- На веб-странице корзины пользователю отображен список товаров добавленных в корзину. 6.4
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено краткое название товара. 6.5
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено количество в наличии. 6.6
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено количество товара добавленного в корзину. 6.7
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено цена товара без скидки. 6.8
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено цена товара со скидкой. 6.9
- На веб-странице корзины в списке товаров цена товара со скидкой отображена в виде цифры перечеркнутой горизонтальной линией. 6.10
- На веб-странице корзины в списке товаров у каждого товара пользователю отображена кнопка "Удалить"/"Delete". 6.11
- Переведено с помощью www.DeepL.com/Translator (бесплатная версия). 9
non-functional:
- Сайт должен иметь мобильную версию. 13
- На момент релиза сайт должен быть совместим с последними версиями мобильных браузеров. 13.1
- Сайт должен быть оптимизирован для устройств поддерживающих последнюю версию мобильных браузеров на момент релиза. 13.2
- Сайт должен иметь десктопную версию. 13.3
- На момент релиза сайт должен быть совместим с последними версиями десктопных браузеров. 13.4
- Сайт должен быть оптимизирован для устройств поддерживающих последнюю версию десктопных браузеров на момент релиза. 13.5
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 13.6
implicit:
- Сайт имеет фасетную навигацию. 2
- Каталог товаров состоит из товаров отображенных в виде списка ячеек товаров. 2.1
- Пользователю не отражены товары не доступные для просмотра. 2.2
- Поисковая строка находится под шапкой веб-страницы слева. 2.3
- Select "Категория"/"Category" товара находится под поисковой строкой. 2.4
- Checkbox "Производитель"/"Brand" товара находится под Select категорий. 2.5
- Checkbox "В наличии"/"In Stock" находится под Checkbox "Производитель"/"Brand". 2.6
- Числовое поле ввода ценового диапазона "Цена"/"Price" находится под Checkbox "В наличии"/"In Stock". 2.7
- Кнопки "Предудыщая"/"Previous" находятся вверху и внизу каталога товаров. 2.8
- Кнопки "Следующая"/"Next" находятся вверху и внизу каталога товаров. 2.9
- Кнопка "Магазин"/"Store" находится справа в шапке Hexlet-store. 2.10
- Кнопка "Корзина"/"Cart" находится в шапке магазина Hexlet-store справа от кнопки "Магазин"/"Store". 2.11
- Accordeon "Язык"/"Language" нахоидится в шапке магазина Hexlet-store справа от кнопки "Корзина"/"Cart". 2.12
- Пользователь может фильтровать товары по нескольким выбранным характеристикам товара одновременно. 3
- Пользователь может фильтровать товары по одной характеристике товара. 3.1
- Фильтрация товара через поисковую строку осуществляется по одинаковым символам и их последовательностью в названии, описании или производителю товара. 3.12
- Рейтинг товара составляется посредством среднего значения с округлением до десятичной дроби с округлением до десятых. 3.13
- Фильтрация по цене должна осуществляться по актуальной цене со скидкой. 3.14
- В ячейке товара отображено краткое название товара. 4
- В ячейке товара отображено основное изображение. 4.1
- В ячейке товара отображено краткое описание. 4.2
- В ячейке товара отображена цена товара. 4.3
- В ячейке товара отображена цена со скидкой. 4.4
- В ячейке товара цена товара со скидкой отображена в виде цифры перечеркнутой горизонтальной линией. 4.5
- В ячейке товара отображено количество товаров в наличии. 4.6
- В ячейке товара отображен производитель товара. 4.7
- В ячейке товара отображена кнопка "В корзину"/"Add to cart". 4.8
- Пользователь может добавлять товар в корзину товаров со страницы каталога товаров нажатием кнопки "В корзину"/"Add to cart". 4.9
- При просмотре подробной информации о товаре основные, дополнительные изображения представлены в виде превью. 5
- При просмотре веб-страницы товара пользователю отображено полное название товара. 5.1
- При просмотре веб-страницы товара пользователю отображено основное изображение товара. 5.2
- При просмотре веб-страницы товара пользователю отображены дополнительные изображения товара. 5.3
- При просмотре веб-страницы товара пользователю отображена полное описание о товара. 5.4
- При просмотре веб-страницы товара пользователю отображен рейтинг товара. 5.5
- При просмотре веб-страницы товара пользователю отображена цена товара. 5.6
- При просмотре веб-страницы товара пользователю отображена цена товара со скидкой. 5.7
- При просмотре веб-страницы товара цена товара со скидкой отображена в виде цифры перечеркнутой горизонтальной линией. 5.8
- При просмотре веб-страницы товара пользователю отображен процент скидки. 5.9
- При просмотре веб-страницы товара пользователю отображено количество товара в наличии. 5.10
- При просмотре веб-страницы товара пользователю отображена кнопка "В корзину"/"Add to cart". 5.11
- При просмотре веб-страницы товара пользователю отображена кнопка "тэг" категории товара. 5.12
- При просмотре веб-страницы товара пользователю отображен производитель товара. 5.13
- Нажатие кнопки "Магазин"/"Store" пользователь возвращается на веб-страницу каталога товаров. 7
- Нажатие кнопки "Корзина"/"Cart" пользователь попадает на веб-страницу корзины пользователя. 7.1
- Нажатие на accordeon "Язык"/"Language" пользователь может выбрать язык отображения информации в WEB-приложении из выпадающего списка. 7.2
- В выпадающем списке accordeon "Язык"/"Language" пользователю отображены кнопки "Русский" и "English". 7.3
- Нажатие на кнопку "Русский" текстовая информация на веб страницах должна быть отображена на русском языке. 7.4
- Нажатие на кнопку "English" текстовая информация на веб страницах должна быть отображена на английском языке. 7.5
- Нажатие на ячейку товара направляет пользователя на веб-страницу товара. 7.6
- Нажатие на кнопку "В корзину"/"Add to cart" добавляет товар в корзину. 7.7
- При добавлении товара в корзину рядом с кнопкой "Корзина"/"Cart" появляется иконка с количеством добавленного товара. 7.8
- Нажатие на "тег" категории товара, пользователю отображается страница каталога товаров со списоком товаров данной категории. 7.9
- Нажатие кнопки "Очистить корзину"/"Clear cart" удаляются все товары находящиеся в корзине. 7.10
- Нажатие кнопки "Продолжить покупки"/"Continue shopping" из корзины пользователь переходит на страницу каталога товаров. 7.11
- Нажатие кнопки "Оформить заказ"/"Checkout" происходит размещение заказа в интернет-магазине. 7.12
- Нажатие кнопки "Удалить"/"Delete" удаляет товар из корзины. 7.13
- Нажатие кнопки "Следующая"/"Next" страницы каталога товаров переключаются вперед. 7.14
- Нажатие кнопки "Предудыщая"/"Previous" страницы каталога товаров переключаются назад. 7.15
- Нажатие кнопки "Закрыть"/"Close" закрывает модальное окно "Заказ успешно формлен"/"Order placed successfully". 7.16
- Нажатие кнопки "X" закрывает модальное окно "Заказ успешно формлен"/"Order placed successfully". 7.17
- Значение числового поля ценового диапазона "Цена"/"Price" положительные целые числа от 0 до 11190. 7.18
- Функция поиска по ценовому диапазону работает при значении числового поля "От"/"From" "<" или "=" значению числового поля "До"/"To". 7.18.1
- При заполнении только числового поля "От"/"From", числовое поле "До"/"To" по умолчанию принимает значение "11190". 7.18.2
- При заполнении только числового поля "До"/"To", числовое поле "От"/"From" по умолчанию принимает значение "0". 7.18.3
- При незаполнении числовых полей ценового диапазона, они принимают значения по умолчанию "От"/"From" по умолчанию принимает значение "0", "До"/"To" по умолчанию принимает значение "11190". 7.18.4
- Числовое поле "Цена"/"Price" разделено на 2 части "От"/"From" и "До"/"To". 7.19
- Каждая часть числового поля имеет переключатель "Up-Down" для введения ценового диапазона с шагом в 1 единицу. 7.20
- Максимальное количество символов для поисковой строки не более 150 символов. 7.21
- Максимальное количество символов числового поля 7. 7.22
- Перевод должен быть осуществлен на русском и английском языке. 9.1
- При смене языкового отображения веб-страницы название товара остается неизменным. 9.2
- При смене языкового отображения веб-страницы название производителя остается неизменным. 9.3
- Содержимое корзины хранится в сессии браузера. 10
- Формат изображений товара JPEG, JPG, PNG. 10.1
- Разрешение изображений товара от 200х200 до 1920×1080 пикселей. 10.2
- Размер изображений товара не более 8 МБ. 10.2
- Общее количество изображений товара не более 5 штук. 10.3
- Название товара должно содержать не более 150 символов. 10.4
- Название товара состоит из символов русского языка или английского языка, или обоих языков одновременно. 10.5
- Название товара может содержать спецсимволы . , ; ( ) - / & ". 10.6
- Описание товара состоит из символов русского языка или английского языка, или обоих языков одновременно. 10.7
- Описание товара может содержать спецсимволы. 10.8
- Описание товара должно содержать не более 500 символов. 10.9
- Регистрация осуществляется через создание логин/пароль. 11
- Регистрация осуществляется через введения email и создания пароля. 11.1
- Регистрация осуществляется через введение номера мобильного телефона и создания пароля. 11.2
- Пароль должен содержать от 8 до 25 символов, включая от 1 до 5 спецсимволов. 11.3
- Логин должен содержать от 6 до 20 символов. 11.4
- Логин не должен содержать спецсимволы и пробелы. 11.5
- Авторизация осуществляется через введение пары email/пароль, логин/пароль, телефон/пароль. 12
