requirements: | 
functional:
- Сайт должен быть безопасным и защищать данные пользователя.
- Переведено с помощью www.DeepL.com/Translator (бесплатная версия).
- Пользователь должен иметь возможность искать товары по ключевому слову или категории.
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть способен обрабатывать большое количество трафика.
- Сайт должен быть доступен на различных устройствах.
- Сайт должен иметь мобильную версию.
implicit:
- Ни одному другому пользователю не отражены персональные данные другого пользователя.
- Ни одному другому пользователю не отражено содержимое корзины другого пользователя.
- На момент релиза сайт должен быть совместим с последними версиями десктопных браузеров.
- На момент релиза сайт должен быть совместим с последними версиями мобильних браузеров.
- Сайт должен быть доступен на устройствах поддерживающих последнюю версию десктопных браузеров на момент релиза.
- Сайт должен быть доступен на устройствах поддерживающих последнюю версию мобильных браузеров на момент релиза.
- Сайт должен иметь десктопную версию.
- Пользователь может фильтровать товары по нескольким выбранным характеристикам товара одновременно.
- Пользователь может фильтровать товары по одной характеристике товара.
- Товары фильтруются по цене, цвету, размеру, категориям, ключевым словам в описании, ключевым словам в названии, цене, цене со скидкой, производителю, наличию, рейтингу.
- Пользователю отображены товары доступные для просмотра.
- Пользователю не отражены товары не доступные для просмотра.
- Корзина имеет отдельную страницу.
- Пользователь может удалять товары из корзины.
- Корзина должна отображать сумму стоимости товаров, находящихся в корзине.
- Корзина должна отображать информацию о товарах название, количество в наличии, количество в корзине, цену товара, цену товара со скидкой.
- Из корзины пользователь может перейти на страницу оплаты.
- Из корзины пользователь может вернуться на страницу каталога товаров.
- Корзина хранится в сессии браузера.
- Оплата товара производится на отдельной странице.
- Подробная информация о товаре может содержать изображение товара, название, категорию, цену, цену со скидкой, описание, рейтинг, количество товара в наличии, процент скидки.
- Данные сайта должны быть отражены на английском, русском языке.
- Сайт должен иметь возможность смены языка отображения.
- Пользователи должы иметь возможность оценивать товар посредством составления рейтинга в ктаалоге товаров.
