requirements: | 
functional:
- Защита конфиденциальной информации о  пользователе. 1.1
- Переведено с помощью www.DeepL.com/Translator (бесплатная версия). 1.2
- Поиск товаров по символам в названии товара. 1.3.2
- Поиск товаров по категории товаров. 1.3.3
- Фильтрация товаров по цене. 1.4.1
- Фильтрация товаров по цвету. 1.4.2
- Фильтрация товаров по размеру. 1.4.3
- Фильтрация товаров по категории товара. 1.4.4
- Фильтрация товаров по бренду товара. 1.4.5
- Фильтрация товаров по наличию товара. 1.4.6
- Фильтрация товаров по рейтингу. 1.4.7
- Пользователю отображено краткое название товара в ячейке товара. 1.6.2
- Пользователю отображено основное изображение товара в ячейке товара. 1.6.3
- Пользователю отображена краткое описание товара в ячейке товара. 1.6.4
- Пользователю отображена цена товара в ячейке товара. 1.6.5
- Пользователю отображена цена со скидкой в ячейке товара. 1.6.6
- Цена товара со скидкой в ячейке товара отображена в виде цифры перечеркнутой горизонтальной линией. 1.6.6.1
- Пользователю отображено количество товаров в наличии в ячейке товара. 1.6.7
- Пользователю отображена кнопка "В корзину"/"Add to cart" в ячейке товара. 1.6.8
- При просмотре веб-страницы товара пользователю отображено полное название товара 1.7.1
- При просмотре веб-страницы товара пользователю отображено основное изображение товара. 1.7.2
- При просмотре веб-страницы товара пользователю отображены дополнительные изображения товара. 1.7.2.1
- При просмотре веб-страницы товара пользователю отображена полное описание о товара. 1.7.3
- При просмотре веб-страницы товара пользователю отображен рейтинг товара. 1.7.4
- При просмотре веб-страницы товара пользователю отображена цена товара. 1.7.5
- При просмотре веб-страницы товара пользователю отображена цена товара со скидкой. 1.7.6
- При просмотре веб-страницы товара цена товара со скидкой отображена в виде цифры перечеркнутой горизонтальной линией. 1.7.6.1
- При просмотре веб-страницы товара пользователю отображен процент скидки. 1.7.7
- При просмотре веб-страницы товара пользователю отображено количество товара в наличии. 1.7.8
- При просмотре веб-страницы товара пользователю отображена кнопка "В корзину"/"Add to cart". 1.7.9
- При просмотре веб-страницы товара пользователю отображен тэг категории товара. 1.7.10
- Пользователь имеет возможность добавлять товары в корзину нажатием кнопки "В корзину"/"Add to cart". 1.8
- Пользователь имеет возможность просматривать содержимое корзины. 1.9
- На веб-странице корзины пользователю отображена кнопка "Очистить корзину"/"Clear cart". 1.9.2
- На веб-странице корзины пользователю отображена кнопка "Продолжить покупки"/"Continue shopping". 1.9.3
- На веб-странице корзины пользователю отображена кнопка "Оформить заказ"/"Checkout". 1.9.4
- На веб-странице корзины пользователю отображена сумма стоимости добавленных в корзину товаров с учетом скидки. 1.9.5
- На веб-странице корзины пользователю отображен список товаров добавленных в корзину. 1.9.6
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено краткое название товара. 1.9.6.1
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено количество в наличии. 1.9.6.2
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено количество товара добавленного в корзину. 1.9.6.3
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено цена товара без скидки. 1.9.6.4
- На веб-странице корзины в списке товаров у каждого товара пользователю отображено цена товара со скидкой. 1.9.6.5
- Цена товара со скидкой на веб-странице корзины в списке товаров отображена в виде цифры перечеркнутой горизонтальной линией. 1.9.6.5.1
- На веб-странице корзины в списке товаров у каждого товара пользователю отображена кнопка "Удалить"/"Delete". 1.9.6.6
non-functional:
- Сайт должен иметь мобильную версию. 2.1
- На момент релиза сайт должен быть совместим с последними версиями мобильных браузеров. 2.1.1
- Сайт должен быть оптимизирован для устройств поддерживающих последнюю версию мобильных браузеров на момент релиза. 2.1.2
- Сайт должен иметь десктопную версию. 2.2
- На момент релиза сайт должен быть совместим с последними версиями десктопных браузеров. 2.2.1
- Сайт должен быть оптимизирован для устройств поддерживающих последнюю версию десктопных браузеров на момент релиза. 2.2.2
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 2.3
implicit:
- Ни одному другому пользователю не отражены персональные данные другого пользователя. 1.1.1
- Ни одному другому пользователю не отражено содержимое корзины другого пользователя. 1.1.2
- Нажатием на accordeon "Язык"/"Language" пользователь может выбрать язык отображения информации в WEB-приложении из выпадающего списка. 1.2.1
- В выпадающем списоке accordeon "Язык"/"Language" пользователю отображена кнопка "Русский". 1.2.2
- При нажатии на кнопку "Russian" в выпадающем списоке accordeon "Язык"/"Language" текстовая информация на веб страницах должна быть отображена на русском языке. 1.2.2.1
- В выпадающем списоке accordeon "Язык"/"Language" пользователю отображена кнопка "English". 1.2.3
- При нажатии на кнопку "English" в выпадающем списоке accordeon "Язык"/"Language" текстовая информация на веб страницах должна быть отображена на английском языке. 1.2.3.1
- При смене языкового отображения веб-страницы название товара остается неизменным. 1.2.4
- При смене языкового отображения веб-страницы название производителя остается неизменным. 1.2.5
- Сайт имеет фасетную навигацию. 1.3
- Поисковая строка находится под шапкой веб-страницы слева. 1.3.1
- Select "Категория"/"Category" товара находится под поисковой строкой. 1.3.4
- Checkbox "Производитель"/"Brand" товара находится под Select категорий. 1.3.5
- Checkbox "В наличии"/"In Stock" находится под Checkbox "Производитель"/"Brand". 1.3.6
- Числовое поле ввода ценового диапазона "Цена"/"Price" находится под Checkbox "В наличии"/"In Stock". 1.3.7
- Значение числового поля ценового диапазона "Цена"/"Price" положительные целые числа от 0 до 11190. 1.3.8
- Числовое поле "Цена"/"Price" имеет переключатели для ручного введения ценового диапазона с шагом в 1 единицу. 1.3.9
- Пользователь может фильтровать товары по нескольким выбранным характеристикам товара одновременно. 1.4.8
- Пользователь может фильтровать товары по одной характеристике товара. 1.4.9
- На главной странице товары отображены в виде списка ячеек товаров. 1.6
- Пользователь имеет возможность просматирвать список в виде ячеек товаров. 1.6.1
- Пользователю отображен бренд товара в ячейке товара. 1.6.9
- Пользователь имеет возможность переходить на веб-сайт товара. 1.7
- При просмотре подробной информации о товаре основные, дополнительные изображения представлены в виде превью. 1.7.2.3
- Просматривая страницу подробной информации о товаре, нажимая на тэг категории товара, пользователю отображается список товаров данной категории. 1.7.10.1
- При просмотре веб-страницы товара пользователю отображен бренд товара. 1.7.11
- Нажатием кнопки "Корзина"/"Cart" пользователь попадает на веб-страницу корзины пользователя. 1.9.1
- Нажатием кнопки "Очистить корзину"/"Clear cart" удаляются все товары находящиеся в корзине. 1.9.2.1
- Нажатием кнопки "Продолжить покупки"/"Continue shopping" из корзины пользователь переходит на страницу каталога товаров. 1.9.3.1
- Нажатием кнопки "Оформить заказ"/"Checkout" из корзины пользователь переходит на страницу оплаты товара. 1.9.4.1
- В шапке веб-страницы магазина справа отображена кнопка "Магазин"/"Store". 1.10
- При нажатии на конпку "Магазин"/"Store" пользователь возвращается на веб-страницу со списком товаров. 1.10.1
- В шапке веб-страницы магазина справа отображена кнопка "Корзина"/"Cart". 1.11
- При добавлении товара в корзину рядом с кнопкой "Корзина"/"Cart" появляется иконка с количеством добавленного товара. 1.11.1
- В шапке веб страницы магазина справа отображен accordeon "Язык"/"Language". 1.12
- Пользователю не отражены товары не доступные для просмотра. 1.13
- Корзина хранится в сессии браузера. 2.4
- Формат изображений товара JPEG, JPG, PNG. 2.5
- Разрешение изображений товара от 200х200 до 1920×1080 пикселей. 2.5.1
- Размер изображений товара не более 8 МБ. 2.5.2
- Общее количество изображений товара не более 5 штук. 2.5.3
- Название товара должно содержать не более 150 символов. 2.6
- Название товара состоит из символов русского языка или английского языка, или обоих языков одновременно. 2.6.1
- Название товара может содержать спецсимволы . , : ; ( ) - / & ". 2.6.2
- Описание товара должно содержать не более 500 символов. 2.7
- Описание товара состоит из символов русского языка или английского языка, или обоих языков одновременно. 2.7.1
- Описание товара может содержать спецсимволы. 2.7.3
- Зарегестрированный пользователь может выставлять рейтинг товару по 5ти бальной шкале, от 1 до 5. 1.14
- Рейтинг товара составляется посредством среднего значения с округлением до десятичной дроби с округлением до десятых. 1.14.1
- Поиск товара через поисковую строку осуществляется по одинаковым символам и их последовательностью в названии, описании или бренде товара. 1.15
- Регистрация осуществляется через создание логин/пароль. 1.16
- Регистрация осуществляется через введения email и создания пароля. 1.17
- Регистрация осуществляется через введение номера мобильного телефона и создания пароля. 1.18
- Авторизация осуществляется через введение пары email/пароль, логин/пароль, телефон/пароль. 1.19
- Пароль должен содержать от 8 до 25 символов, включая от 1 до 5 спецсимволов. 2.8
- Логин должен содержать от 6 до 20 символов. 2.9
- Логин не должен содержать спецсимволы и пробелы. 2.10
